#############################################################################
# Makefile for building: mviaPreview
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mo. Jan 21 14:15:45 2013
# Project:  mviaPreview.pro
# Template: app
# Command: /home/krunix/data/qt474/bin/qmake -o Makefile mviaPreview.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I../data/qt474/mkspecs/linux-g++ -I. -I../data/qt474/include/QtCore -I../data/qt474/include/QtGui -I../data/qt474/include/QtOpenGL -I../data/qt474/include -I$(MVIMPACT_ACQUIRE_SOURCE_DIR) -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/krunix/data/qt474/lib
LIBS          = $(SUBLIBS)  -L/home/krunix/data/qt474/lib -L/usr/X11R6/lib $(MVIMPACT_ACQUIRE_SOURCE_DIR)/lib/x86/libosAbstraction.a -L$(MVIMPACT_ACQUIRE_SOURCE_DIR)/lib/x86 -lmvDeviceManager -lmvPropHandling -lm -ldl -lrt -lQtOpenGL -L/home/krunix/data/qt474/lib -L/usr/X11R6/lib -lQtGui -lQtCore -lpthread -lGLU -lGL 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/krunix/data/qt474/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gleswidget.cpp \
		workerthread.cpp moc_mainwindow.cpp \
		moc_gleswidget.cpp \
		moc_workerthread.cpp \
		qrc_mviapreview.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gleswidget.o \
		workerthread.o \
		moc_mainwindow.o \
		moc_gleswidget.o \
		moc_workerthread.o \
		qrc_mviapreview.o
DIST          = ../data/qt474/mkspecs/common/g++.conf \
		../data/qt474/mkspecs/common/unix.conf \
		../data/qt474/mkspecs/common/linux.conf \
		../data/qt474/mkspecs/qconfig.pri \
		../data/qt474/mkspecs/modules/qt_webkit_version.pri \
		../data/qt474/mkspecs/features/qt_functions.prf \
		../data/qt474/mkspecs/features/qt_config.prf \
		../data/qt474/mkspecs/features/exclusive_builds.prf \
		../data/qt474/mkspecs/features/default_pre.prf \
		../data/qt474/mkspecs/features/debug.prf \
		../data/qt474/mkspecs/features/default_post.prf \
		../data/qt474/mkspecs/features/unix/thread.prf \
		../data/qt474/mkspecs/features/qt.prf \
		../data/qt474/mkspecs/features/unix/opengl.prf \
		../data/qt474/mkspecs/features/moc.prf \
		../data/qt474/mkspecs/features/warn_on.prf \
		../data/qt474/mkspecs/features/resources.prf \
		../data/qt474/mkspecs/features/uic.prf \
		../data/qt474/mkspecs/features/yacc.prf \
		../data/qt474/mkspecs/features/lex.prf \
		../data/qt474/mkspecs/features/include_source_dir.prf \
		mviaPreview.pro
QMAKE_TARGET  = mviaPreview
DESTDIR       = 
TARGET        = mviaPreview

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mviaPreview.pro  ../data/qt474/mkspecs/linux-g++/qmake.conf ../data/qt474/mkspecs/common/g++.conf \
		../data/qt474/mkspecs/common/unix.conf \
		../data/qt474/mkspecs/common/linux.conf \
		../data/qt474/mkspecs/qconfig.pri \
		../data/qt474/mkspecs/modules/qt_webkit_version.pri \
		../data/qt474/mkspecs/features/qt_functions.prf \
		../data/qt474/mkspecs/features/qt_config.prf \
		../data/qt474/mkspecs/features/exclusive_builds.prf \
		../data/qt474/mkspecs/features/default_pre.prf \
		../data/qt474/mkspecs/features/debug.prf \
		../data/qt474/mkspecs/features/default_post.prf \
		../data/qt474/mkspecs/features/unix/thread.prf \
		../data/qt474/mkspecs/features/qt.prf \
		../data/qt474/mkspecs/features/unix/opengl.prf \
		../data/qt474/mkspecs/features/moc.prf \
		../data/qt474/mkspecs/features/warn_on.prf \
		../data/qt474/mkspecs/features/resources.prf \
		../data/qt474/mkspecs/features/uic.prf \
		../data/qt474/mkspecs/features/yacc.prf \
		../data/qt474/mkspecs/features/lex.prf \
		../data/qt474/mkspecs/features/include_source_dir.prf \
		/home/krunix/data/qt474/lib/libQtOpenGL.prl \
		/home/krunix/data/qt474/lib/libQtGui.prl \
		/home/krunix/data/qt474/lib/libQtCore.prl
	$(QMAKE) -o Makefile mviaPreview.pro
../data/qt474/mkspecs/common/g++.conf:
../data/qt474/mkspecs/common/unix.conf:
../data/qt474/mkspecs/common/linux.conf:
../data/qt474/mkspecs/qconfig.pri:
../data/qt474/mkspecs/modules/qt_webkit_version.pri:
../data/qt474/mkspecs/features/qt_functions.prf:
../data/qt474/mkspecs/features/qt_config.prf:
../data/qt474/mkspecs/features/exclusive_builds.prf:
../data/qt474/mkspecs/features/default_pre.prf:
../data/qt474/mkspecs/features/debug.prf:
../data/qt474/mkspecs/features/default_post.prf:
../data/qt474/mkspecs/features/unix/thread.prf:
../data/qt474/mkspecs/features/qt.prf:
../data/qt474/mkspecs/features/unix/opengl.prf:
../data/qt474/mkspecs/features/moc.prf:
../data/qt474/mkspecs/features/warn_on.prf:
../data/qt474/mkspecs/features/resources.prf:
../data/qt474/mkspecs/features/uic.prf:
../data/qt474/mkspecs/features/yacc.prf:
../data/qt474/mkspecs/features/lex.prf:
../data/qt474/mkspecs/features/include_source_dir.prf:
/home/krunix/data/qt474/lib/libQtOpenGL.prl:
/home/krunix/data/qt474/lib/libQtGui.prl:
/home/krunix/data/qt474/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mviaPreview.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mviaPreview1.0.0 || $(MKDIR) .tmp/mviaPreview1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mviaPreview1.0.0/ && $(COPY_FILE) --parents mainwindow.h gleswidget.h workerthread.h .tmp/mviaPreview1.0.0/ && $(COPY_FILE) --parents mviapreview.qrc .tmp/mviaPreview1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp gleswidget.cpp workerthread.cpp .tmp/mviaPreview1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/mviaPreview1.0.0/ && (cd `dirname .tmp/mviaPreview1.0.0` && $(TAR) mviaPreview1.0.0.tar mviaPreview1.0.0 && $(COMPRESS) mviaPreview1.0.0.tar) && $(MOVE) `dirname .tmp/mviaPreview1.0.0`/mviaPreview1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mviaPreview1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_gleswidget.cpp moc_workerthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_gleswidget.cpp moc_workerthread.cpp
moc_mainwindow.cpp: gleswidget.h \
		workerthread.h \
		mainwindow.h
	/home/krunix/data/qt474/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_gleswidget.cpp: gleswidget.h
	/home/krunix/data/qt474/bin/moc $(DEFINES) $(INCPATH) gleswidget.h -o moc_gleswidget.cpp

moc_workerthread.cpp: gleswidget.h \
		workerthread.h
	/home/krunix/data/qt474/bin/moc $(DEFINES) $(INCPATH) workerthread.h -o moc_workerthread.cpp

compiler_rcc_make_all: qrc_mviapreview.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mviapreview.cpp
qrc_mviapreview.cpp: mviapreview.qrc \
		picture.ico \
		sun.ico \
		icon1.ico \
		mv.ico \
		playback_play.ico
	/home/krunix/data/qt474/bin/rcc -name mviapreview mviapreview.qrc -o qrc_mviapreview.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/krunix/data/qt474/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		gleswidget.h \
		workerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gleswidget.h \
		workerthread.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gleswidget.o: gleswidget.cpp gleswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gleswidget.o gleswidget.cpp

workerthread.o: workerthread.cpp workerthread.h \
		gleswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workerthread.o workerthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_gleswidget.o: moc_gleswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gleswidget.o moc_gleswidget.cpp

moc_workerthread.o: moc_workerthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_workerthread.o moc_workerthread.cpp

qrc_mviapreview.o: qrc_mviapreview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mviapreview.o qrc_mviapreview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

